services:
  - type: web
    name: personal-budget-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn budget_api.wsgi:application"
    envVars:
      DJANGO_SETTINGS_MODULE: "budget_api.settings"
