services:
  - type: web
    name: personal-budget-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn budget_api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: budget_api.settings
